"use client";
import { CheckCircle2, XCircle } from "lucide-react";
import { NiubizCheckout } from "@/modules/afiliaciones/payments/Components/NiubizCheckout";
import { PaymentLoadingOverlay } from "@/modules/afiliaciones/payments/Components/PaymentLoadingOverlay";
import type { BillingDataInput } from "@/modules/afiliaciones/payments/DTOs/billing.schema";
import type { CreatePaymentResponse } from "@/modules/afiliaciones/payments/Models/PaymentResponse";
export type PaymentUiState = "IDLE" | "PREPARING_CHECKOUT" | "CHECKOUT_OPEN" | "PROCESSING_PAYMENT" | "CHECKOUT_ERROR" | "PAYMENT_FAILED" | "PAYMENT_SUCCESS" | "PAYMENT_UNCERTAIN";
interface Details { transactionId?: string; authorizationCode?: string; }
interface Props { billingData: BillingDataInput; confirmed: boolean; onConfirmedChange: (v: boolean) => void; result: CreatePaymentResponse | null; loading: boolean; error: string | null; onRetry: () => void; paymentUiState: PaymentUiState; onCheckoutStateChange: (s: PaymentUiState) => void; failureMessage?: string | null; failureCode?: string | null; restoredPayment?: Details | null; affiliateType?: string; onFinish?: () => void; }
export default function PaymentProcessStep({ billingData, confirmed, onConfirmedChange, result, loading, error, onRetry, paymentUiState, onCheckoutStateChange, failureMessage, failureCode, restoredPayment, affiliateType, onFinish }: Props) {
  const total = result ? `S/ ${result.amount.toFixed(2)}` : "Monto protegido en el servidor";
  const locked = ["PREPARING_CHECKOUT", "CHECKOUT_OPEN", "PROCESSING_PAYMENT"].includes(paymentUiState);
  const breakdown = result?.registrationAmount != null && result.membershipFeeAmount != null;
  return <section className="relative overflow-hidden rounded-3xl border border-gray-200 bg-white shadow-sm" aria-busy={locked}><div className="border-b bg-[#f4f5f7] px-8 py-5 text-center"><h3 className="text-sm font-bold text-slate-800">Finalizar inscripción y pago</h3></div><div className="mx-auto max-w-xl space-y-5 p-6 sm:p-8">
    {paymentUiState === "PAYMENT_FAILED" && <div className="rounded-2xl border border-rose-200 bg-rose-50 p-5 text-sm text-rose-800"><div className="flex items-center gap-2 font-black"><XCircle size={18}/>Pago no aprobado</div><p>{failureMessage}</p>{failureCode && <p>Código de soporte: {failureCode}</p>}</div>}
    <div className="rounded-2xl border border-[#E8D09E] bg-[#FCFAF6] p-5"><p className="mb-4 text-xs font-black uppercase tracking-wide text-[#9A7739]">Resumen final antes del pago</p><dl className="space-y-3 text-sm"><div><dt>Participante / Razón social</dt><dd className="font-bold">{billingData.razonSocial}</dd></div><div><dt>Categoría / Tipo de afiliación</dt><dd>{affiliateType ?? "No disponible"}</dd></div>{breakdown && <><div className="flex justify-between border-t pt-3"><dt>Inscripción</dt><dd>S/ {result.registrationAmount!.toFixed(2)}</dd></div><div className="flex justify-between"><dt>Cuota de afiliación</dt><dd>S/ {result.membershipFeeAmount!.toFixed(2)}</dd></div></>}<div className="flex justify-between border-t pt-3"><dt className="font-black uppercase">Total a pagar</dt><dd className="text-lg font-black text-[#9A7739]">{total}</dd></div></dl></div>
    <div className="rounded-2xl border border-[#E8D09E] bg-[#FFFCF5] p-5"><div className="flex items-center gap-2 font-black"><CheckCircle2 size={17}/>Confirmación de {billingData.tipoDocumento === "RUC" ? "Factura" : "Boleta de Venta"}</div>{billingData.tipoDocumento === "RUC" && <p className="mt-3">Usted está solicitando una <strong>FACTURA COMERCIAL</strong> a nombre de <strong>{billingData.razonSocial}</strong> con RUC <strong>{billingData.numeroDocumento}</strong>.</p>}<label className="mt-4 flex gap-3"><input type="checkbox" disabled={locked} checked={confirmed} onChange={(event) => onConfirmedChange(event.target.checked)} /><span>Confirmo que los datos de facturación son correctos.</span></label></div>
    {paymentUiState === "PAYMENT_SUCCESS" && result && <div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-5"><p className="font-black">Pago realizado correctamente</p><p>Monto: {total}</p><p>Operación: {restoredPayment?.transactionId ?? "No disponible"}</p><button type="button" onClick={onFinish}>Finalizar</button></div>}{loading && <p>Preparando pago...</p>}{error && <p>{error}</p>}{result?.checkout && <NiubizCheckout config={result.checkout} disabled={!confirmed || locked} onStateChange={onCheckoutStateChange}/>} {paymentUiState === "PAYMENT_FAILED" && <button type="button" onClick={onRetry}>Intentar nuevamente</button>}
  </div>{paymentUiState === "PREPARING_CHECKOUT" && <PaymentLoadingOverlay title="Preparando pago" description="Estamos conectando con la pasarela segura de Niubiz." />}{paymentUiState === "PROCESSING_PAYMENT" && <PaymentLoadingOverlay title="Procesando pago" description="Estamos confirmando la operación." />}</section>;
}
