"use client";
import { useState } from "react";
import { CheckCircle2, Clock3, GraduationCap, LoaderCircle, RefreshCw, ShieldAlert, UserRound } from "lucide-react";
import { DataTable, type DataTableColumn } from "@/modules/shared/Components/DataManagement";
import { AssociateIntegrationActionMenu } from "./AssociateIntegrationActionMenu";
import { affiliateLabels, AssociateIntegrationRow, AssociateIntegrationStatus, formatAssociateIntegrationDate, triggerLabels } from "./associateIntegration.types";
const statusPresentation: Record<AssociateIntegrationStatus, { label: string; Icon: typeof CheckCircle2; className: string; indicator: string }> = { SYNCED: { label: "Sincronizado", Icon: CheckCircle2, className: "border-emerald-100 bg-emerald-50 text-emerald-700", indicator: "border-emerald-400" }, PENDING: { label: "Pendiente de envío", Icon: Clock3, className: "border-sky-100 bg-sky-50 text-sky-700", indicator: "border-sky-400" }, PROCESSING: { label: "Procesando", Icon: LoaderCircle, className: "border-indigo-100 bg-indigo-50 text-indigo-700", indicator: "border-indigo-400" }, RETRYABLE: { label: "Reintento disponible", Icon: RefreshCw, className: "border-amber-100 bg-amber-50 text-amber-800", indicator: "border-amber-400" }, FAILED: { label: "Requiere revisión", Icon: ShieldAlert, className: "border-rose-100 bg-rose-50 text-rose-700", indicator: "border-rose-300" } };
export function AssociateIntegrationStatusBadge({ status }: { status: AssociateIntegrationStatus }) { const { label, Icon, className } = statusPresentation[status]; return <span className={`inline-flex items-center gap-1.5 rounded-md border px-2 py-1 text-[10px] font-bold ${className}`}><Icon size={12} className={status === "PROCESSING" ? "animate-spin" : ""} />{label}</span>; }
const getInitials = (name?: string | null) => (name ?? "No disponible").split(/\s+/).filter(Boolean).slice(0, 2).map((part) => part[0]).join("").toUpperCase();
const attemptTone: Record<AssociateIntegrationStatus, string> = { SYNCED: "bg-emerald-500", PENDING: "bg-slate-300", PROCESSING: "bg-sky-500", RETRYABLE: "bg-amber-500", FAILED: "bg-rose-400" };
type Props = { rows: AssociateIntegrationRow[]; onOpenDetail: (id: number, tab?: "Resumen" | "Payload SIE") => void; onRetry: (id: number) => void };
export function AssociateIntegrationTable({ rows, onOpenDetail, onRetry }: Props) { const [selectedIds, setSelectedIds] = useState<Set<number>>(new Set()); const allSelected = rows.length > 0 && rows.every((row) => selectedIds.has(row.integrationId)); const toggleRow = (id: number) => setSelectedIds((current) => { const next = new Set(current); next.has(id) ? next.delete(id) : next.add(id); return next; }); const toggleAll = () => setSelectedIds(allSelected ? new Set() : new Set(rows.map((row) => row.integrationId))); const columns: DataTableColumn<AssociateIntegrationRow>[] = [
  { key: "selection", header: <input aria-label="Seleccionar registros visibles" type="checkbox" checked={allSelected} onChange={toggleAll} className="h-4 w-4 cursor-pointer accent-[#C5A059]" />, align: "center", width: "52px", render: (item) => <input aria-label={`Seleccionar ${item.applicationCode}`} type="checkbox" checked={selectedIds.has(item.integrationId)} onChange={() => toggleRow(item.integrationId)} className="h-4 w-4 cursor-pointer accent-[#C5A059]" /> },
  { key: "application", header: "Expediente", minWidth: "190px", render: (item) => <div className={`border-l-2 pl-3 ${statusPresentation[item.status].indicator}`}><p className="font-semibold text-slate-800">{item.applicationCode}</p><p className="mt-1 text-[11px] font-medium text-slate-400">#{item.applicationId} · {triggerLabels[item.trigger]}</p></div> },
  { key: "associate", header: "Asociado", minWidth: "245px", render: (item) => <div className="flex items-center gap-3"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-[#fdfaf5] text-[11px] font-black text-[#8a682b]">{getInitials(item.associate?.fullName)}</span><div className="min-w-0"><p className="truncate font-semibold text-slate-800">{item.associate?.fullName ?? "No disponible"}</p><p className="mt-1 text-[11px] font-medium text-slate-400">{item.associate?.documentType ?? "—"}: {item.associate?.maskedDocumentNumber ?? "—"}</p></div></div> },
  { key: "type", header: "Tipo", minWidth: "125px", render: (item) => { const Icon = item.affiliateType === "STUDENT" ? GraduationCap : UserRound; return <span className="inline-flex items-center gap-1.5 rounded-md bg-slate-100 px-2 py-1 text-xs font-semibold text-slate-600"><Icon size={13} />{affiliateLabels[item.affiliateType]}</span>; } },
  { key: "status", header: "Estado SIE", minWidth: "170px", render: (item) => <AssociateIntegrationStatusBadge status={item.status} /> },
  { key: "attempts", header: "Intentos", align: "center", minWidth: "90px", render: (item) => <div className="inline-flex flex-col items-center"><span className="text-sm font-semibold text-slate-700">{item.attempts}</span><span aria-label={`${item.attempts} intentos`} className="mt-1 flex gap-1">{Array.from({ length: 4 }, (_, index) => <span key={index} className={`h-1.5 w-1.5 rounded-full ${index < Math.min(item.attempts, 4) ? attemptTone[item.status] : "bg-slate-200"}`} />)}</span></div> },
  { key: "code", header: "Código SIE", minWidth: "115px", render: (item) => <span className="font-mono text-sm font-semibold text-slate-700">{item.externalAssociateCode ?? "—"}</span> },
  { key: "lastAttempt", header: "Último intento", minWidth: "165px", render: (item) => item.lastAttemptAt ? <div><p className="whitespace-nowrap text-xs font-medium text-slate-600">{formatAssociateIntegrationDate(item.lastAttemptAt)}</p><p className="mt-1 text-[11px] text-slate-400">Registro más reciente</p></div> : <span className="text-xs font-medium text-slate-400">Sin intentos aún</span> },
  { key: "actions", header: "Acciones", align: "center", width: "88px", render: (item) => <AssociateIntegrationActionMenu row={item} onDetail={() => onOpenDetail(item.integrationId, "Resumen")} onPayload={() => onOpenDetail(item.integrationId, "Payload SIE")} onRetry={() => onRetry(item.integrationId)} /> },
]; return <DataTable data={rows} columns={columns} rowKey={(row) => row.integrationId} minWidth="1370px" rowClassName={(row) => selectedIds.has(row.integrationId) ? "bg-[#fdfaf5]" : ""} />; }
