/* eslint-disable @typescript-eslint/no-explicit-any -- Prisma transaction double is intentionally partial. */
import { beforeEach, describe, expect, it, vi } from "vitest";
import { Prisma } from "@prisma/client";

const state = vi.hoisted(() => ({ detected: vi.fn(), rows: [] as any[], audits: [] as any[] }));
const now = () => new Date();
const db = vi.hoisted(() => ({ operationalAlertTracking: {} as any, auditLog: {} as any }));

vi.mock("@/lib/prisma", () => ({ prisma: db }));
vi.mock("./OperationalAlertsService", () => ({ operationalAlertsService: { detectAll: state.detected } }));

function wire() {
  db.operationalAlertTracking.findUnique = vi.fn(async ({ where }: any) => state.rows.find((row) => row.alertKey === where.alertKey) ?? null);
  db.operationalAlertTracking.create = vi.fn(async ({ data }: any) => { const row = { id: state.rows.length + 1, firstDetectedAt: now(), lastDetectedAt: now(), assignedUserId: null, resolvedAt: null, resolvedByUserId: null, application: { applicationCode: `APP-${data.applicationId}`, person: null }, ...data }; state.rows.push(row); return row; });
  db.operationalAlertTracking.createMany = vi.fn(async ({ data }: any) => { for (const item of data) if (!state.rows.some((row) => row.alertKey === item.alertKey)) await db.operationalAlertTracking.create({ data: item }); return { count: data.length }; });
  db.operationalAlertTracking.update = vi.fn(async ({ where, data }: any) => { const row = state.rows.find((item) => item.id === where.id); Object.assign(row, data); return row; });
  db.operationalAlertTracking.findMany = vi.fn(async ({ where, take }: any = {}) => state.rows.filter((row) => !where?.status || where.status.in.includes(row.status)).filter((row) => !where?.alertKey || !where.alertKey.notIn || !where.alertKey.notIn.includes(row.alertKey)).filter((row) => !where?.alertKey?.in || where.alertKey.in.includes(row.alertKey)).slice(0, take));
  db.operationalAlertTracking.groupBy = vi.fn(async ({ where }: any) => ["CRITICAL", "WARNING"].flatMap((severity) => { const count = state.rows.filter((row) => where.status.in.includes(row.status) && row.severity === severity).length; return count ? [{ severity, _count: { _all: count } }] : []; }));
  db.auditLog.create = vi.fn(async ({ data }: any) => { state.audits.push(data); return data; });
  db.auditLog.createMany = vi.fn(async ({ data }: any) => { state.audits.push(...data); return { count: data.length }; });
}

const alert = (id = 1, severity = "WARNING") => ({ id: `PORTAL_ACCESS_CONFLICT:${id}`, type: "PORTAL_ACCESS_CONFLICT", severity, applicationId: id, applicationCode: `APP-${id}`, title: "", message: "", createdAt: new Date().toISOString(), action: { label: "", href: "" } });

describe("OperationalAlertTrackingService", () => {
  beforeEach(() => { state.rows.length = 0; state.audits.length = 0; state.detected.mockReset(); wire(); });
  it("creates an ACTIVE tracking and remains idempotent", async () => { state.detected.mockResolvedValue([alert()]); const { OperationalAlertTrackingService } = await import("./OperationalAlertTrackingService"); const service = new OperationalAlertTrackingService(); await service.synchronize(); const first = state.rows[0]; await service.synchronize(); expect(state.rows).toHaveLength(1); expect(state.rows[0]).toMatchObject({ id: first.id, alertKey: "PORTAL_ACCESS_CONFLICT:1", status: "ACTIVE", assignedUserId: null, resolvedAt: null, resolvedByUserId: null }); expect(state.rows[0].firstDetectedAt).toBe(first.firstDetectedAt); expect(state.audits.filter((audit) => audit.action === "OPERATIONAL_ALERT_CREATED")).toHaveLength(1); });
  it("preserves IN_PROGRESS, resolves disappearance, and reopens the same row", async () => { state.detected.mockResolvedValue([alert()]); const { OperationalAlertTrackingService } = await import("./OperationalAlertTrackingService"); const service = new OperationalAlertTrackingService(); await service.synchronize(); const row = state.rows[0]; row.status = "IN_PROGRESS"; row.assignedUserId = 77; const firstDetected = row.firstDetectedAt; await service.synchronize(); expect(row).toMatchObject({ status: "IN_PROGRESS", assignedUserId: 77 }); state.detected.mockResolvedValue([]); await service.synchronize(); expect(row).toMatchObject({ status: "RESOLVED", resolvedByUserId: null }); expect(row.resolvedAt).toBeTruthy(); state.detected.mockResolvedValue([alert()]); await service.synchronize(); expect(row).toMatchObject({ id: 1, status: "ACTIVE", assignedUserId: null, resolvedAt: null, resolvedByUserId: null }); expect(row.firstDetectedAt).toBe(firstDetected); expect(state.audits.map((audit) => audit.action)).toEqual(expect.arrayContaining(["OPERATIONAL_ALERT_AUTO_RESOLVED", "OPERATIONAL_ALERT_REOPENED"])); });
  it("auto-resolves an existing legacy-open tracking without deleting it, while preserving an already resolved tracking", async () => { state.rows.push({ id: 1, alertKey: "LEGACY:1", applicationId: 1, severity: "WARNING", type: "PORTAL_ACCESS_CONFLICT", status: "ACTIVE", firstDetectedAt: now(), lastDetectedAt: now(), application: { applicationCode: "OLD", person: null } }, { id: 2, alertKey: "LEGACY:2", applicationId: 2, severity: "WARNING", type: "PORTAL_ACCESS_CONFLICT", status: "RESOLVED", firstDetectedAt: now(), lastDetectedAt: now(), resolvedAt: now(), application: { applicationCode: "OLD-2", person: null } }); state.detected.mockResolvedValue([]); const { OperationalAlertTrackingService } = await import("./OperationalAlertTrackingService"); await new OperationalAlertTrackingService().synchronize(); expect(state.rows).toHaveLength(2); expect(state.rows[0].status).toBe("RESOLVED"); expect(state.rows[1].status).toBe("RESOLVED"); });
  it("counts 25 open rows while presenting only 20 without resolving the other five", async () => { state.detected.mockResolvedValue(Array.from({ length: 25 }, (_, index) => alert(index + 1, index < 10 ? "CRITICAL" : "WARNING"))); const { OperationalAlertTrackingService } = await import("./OperationalAlertTrackingService"); const service = new OperationalAlertTrackingService(); await service.synchronize(); const result = await service.list(20); expect(result).toMatchObject({ total: 25, critical: 10, warning: 15 }); expect(result.alerts).toHaveLength(20); await service.synchronize(); expect(state.rows.filter((row) => row.status !== "RESOLVED")).toHaveLength(25); });
  it("applies the application cutoff to the bell list and its totals", async () => { const { OperationalAlertTrackingService } = await import("./OperationalAlertTrackingService"); await new OperationalAlertTrackingService().list(); expect(db.operationalAlertTracking.findMany).toHaveBeenCalledWith(expect.objectContaining({ where: expect.objectContaining({ application: expect.objectContaining({ createdAt: expect.objectContaining({ gte: expect.any(Date) }) }) }) })); expect(db.operationalAlertTracking.groupBy).toHaveBeenCalledWith(expect.objectContaining({ where: expect.objectContaining({ application: expect.objectContaining({ createdAt: expect.objectContaining({ gte: expect.any(Date) }) }) }) })); });
  it("handles concurrent alertKey creation through P2002 without a duplicate", async () => { state.detected.mockResolvedValue([alert()]); wire(); db.operationalAlertTracking.create.mockImplementationOnce(async ({ data }: any) => { state.rows.push({ id: 1, firstDetectedAt: now(), lastDetectedAt: now(), assignedUserId: null, resolvedAt: null, resolvedByUserId: null, application: { applicationCode: "APP-1", person: null }, ...data }); throw new Prisma.PrismaClientKnownRequestError("unique", { code: "P2002", clientVersion: "6.19.3", meta: { target: ["alert_key"] } }); }); const { OperationalAlertTrackingService } = await import("./OperationalAlertTrackingService"); await expect(new OperationalAlertTrackingService().synchronize()).resolves.toMatchObject({ created: 0 }); expect(state.rows).toHaveLength(1); });
});
