import { NextResponse } from "next/server";
import { contextService } from "@/modules/auth/context/service";
import { AssociateProfileService } from "@/modules/afiliaciones/portal/Services/AssociateProfileService";
import { S3StorageService } from "@/modules/shared/Services/S3StorageService";
import { z } from "zod";
export async function GET() { try { const user = await contextService.requireAffiliate(); const profile = await new AssociateProfileService().getForUser(user.id); if (profile?.identity.image) profile.identity.image = await new S3StorageService().getPresignedAvatarUrl(profile.identity.image); return NextResponse.json({ success: true, data: profile }); } catch (error) { return NextResponse.json({ success: false, message: error instanceof Error ? error.message : "No autorizado." }, { status: 403 }); } }
const calendarDate = z.string().regex(/^\d{4}-\d{2}-\d{2}$/);
const schema=z.object({firstName:z.string().trim().min(1).max(150),paternalLastName:z.string().trim().min(1).max(150),maternalLastName:z.string().trim().max(150).nullable(),birthDate:calendarDate.nullable(),gender:z.enum(["MALE","FEMALE","OTHER","PREFER_NOT_TO_SAY"]).nullable(),nationalityId:z.number().int().positive().nullable()});
export async function PATCH(request:Request){try{const user=await contextService.requireAffiliate(),form=await request.formData(),n=(key:string)=>form.get(key)?.toString()||null,data=schema.parse({firstName:form.get("firstName"),paternalLastName:form.get("paternalLastName"),maternalLastName:n("maternalLastName"),birthDate:n("birthDate"),gender:n("gender"),nationalityId:n("nationalityId")?Number(n("nationalityId")):null}),file=form.get("image");let image:{key:string;fileName:string;mimeType:string;sizeBytes:number}|undefined;if(file instanceof File&&file.size){if(!["image/jpeg","image/png","image/webp"].includes(file.type))throw new Error("La fotografía debe ser JPG, PNG o WEBP.");if(file.size>5*1024*1024)throw new Error("La fotografía no puede superar los 5 MB.");image={key:await new S3StorageService().uploadPrivateFile(Buffer.from(await file.arrayBuffer()),file.name,file.type,"afiliaciones/perfiles"),fileName:file.name,mimeType:file.type,sizeBytes:file.size}}const profile=await new AssociateProfileService().updateIdentity(user.id,{...data,...(image?{image}:{})});if(profile?.identity.image)profile.identity.image=await new S3StorageService().getPresignedAvatarUrl(profile.identity.image);return NextResponse.json({success:true,data:profile})}catch(error){return NextResponse.json({success:false,message:error instanceof z.ZodError?"Verifica los datos personales.":error instanceof Error?error.message:"No fue posible actualizar el perfil."},{status:error instanceof z.ZodError?400:403})}}
