import Link from "next/link";
import { PaymentRepository } from "@/modules/afiliaciones/payments/Repositories/PaymentRepository";
import { paymentAuthorizationService } from "@/modules/afiliaciones/payments/Services/PaymentAuthorizationService";
import { cookies } from "next/headers";

export default async function PaymentConfirmedPage({ searchParams }: { searchParams: Promise<{ payment_restore?: string }> }) {
  const { payment_restore: restoreReference } = await searchParams;
  const cookieStore = await cookies();
  const reference = paymentAuthorizationService.verifyRestoreReference(restoreReference, cookieStore.get(paymentAuthorizationService.restoreCookieName)?.value);
  const payment = reference ? await new PaymentRepository().findPaymentConfirmationDetails(reference.paymentId) : null;
  const valid = Boolean(payment && reference && payment.applicationId === reference.applicationId && payment.status === "PAID");
  if (!valid || !payment) return <main className="min-h-screen grid place-items-center bg-slate-50 p-6"><section className="max-w-md rounded-3xl bg-white p-8 text-center shadow"><h1 className="text-xl font-bold text-slate-800">No pudimos confirmar el pago</h1><p className="mt-3 text-slate-600">Consulta nuevamente el estado de tu solicitud.</p><Link className="mt-6 inline-block rounded-xl bg-[#C5A059] px-6 py-3 font-bold text-white" href="/consulta">Volver a consulta</Link></section></main>;
  const name = payment.application.person ? [payment.application.person.firstName, payment.application.person.paternalLastName, payment.application.person.maternalLastName].filter(Boolean).join(" ") : "Postulante";
  const amount = new Intl.NumberFormat("es-PE", { style: "currency", currency: payment.currency, minimumFractionDigits: 2 }).format(payment.totalAmount).replace("PEN", "S/");
  const maskedEmail = payment.application.email.replace(/^(.{2}).*(@.*)$/, "$1****$2");
  return <main className="min-h-screen bg-slate-50 p-6 grid place-items-center"><section className="w-full max-w-2xl overflow-hidden rounded-3xl bg-white shadow-xl"><header className="bg-[#152238] px-8 py-10 text-center text-white"><p className="font-bold tracking-widest text-[#C5A059]">PAGO CONFIRMADO</p><h1 className="mt-3 text-3xl font-black">Pago realizado correctamente</h1><p className="mt-3 text-white/85">Tu proceso de afiliación al Instituto de Ingenieros de Minas del Perú ha sido completado.</p></header><div className="space-y-6 p-8"><p className="text-slate-700">Estimado(a) <strong>{name}</strong>, tu pago ha sido procesado con éxito.</p><div className="rounded-2xl border border-[#E8D09E] bg-[#FCFAF6] p-6"><h2 className="font-black text-[#8A671D]">RESUMEN DE TU PAGO</h2><dl className="mt-4 space-y-3 text-sm"><div className="flex justify-between gap-4"><dt className="text-slate-500">N° de operación</dt><dd className="font-bold">{payment.transactionId ?? payment.id}</dd></div><div className="flex justify-between gap-4"><dt className="text-slate-500">Fecha</dt><dd className="font-bold">{payment.paymentDate ? new Intl.DateTimeFormat("es-PE", { dateStyle: "medium", timeStyle: "short" }).format(payment.paymentDate) : "—"}</dd></div><div className="flex justify-between gap-4"><dt className="text-slate-500">Método</dt><dd className="font-bold">Niubiz – Tarjeta</dd></div><div className="flex justify-between gap-4"><dt className="text-slate-500">Estado</dt><dd className="font-bold text-emerald-700">Pago aprobado</dd></div></dl><p className="mt-6 text-xs font-bold text-slate-500">TOTAL PAGADO</p><p className="text-3xl font-black text-[#8A671D]">{amount}</p></div>{payment.billing && <div className="rounded-2xl border border-slate-200 p-5 text-sm"><h2 className="font-black text-slate-700">DATOS DE FACTURACIÓN</h2><p className="mt-3 font-bold">{payment.billing.businessName}</p><p className="text-slate-600">{payment.billing.taxId}</p>{payment.billing.billingAddress && <p className="text-slate-600">{payment.billing.billingAddress}</p>}</div>}<div className="rounded-2xl bg-slate-50 p-5 text-sm text-slate-700"><h2 className="font-black">CONFIRMACIÓN ENVIADA</h2><p className="mt-2">Enviamos la constancia y el resumen a {maskedEmail}.</p></div><Link href="/consulta" className="block rounded-xl bg-[#C5A059] px-6 py-3 text-center font-extrabold text-white">VOLVER A CONSULTA</Link></div></section></main>;
}
