import type { Metadata } from "next";
import { Geist, Geist_Mono, Montserrat } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const montserrat = Montserrat({ 
  subsets: ["latin"],
  weight: ['400', '500', '600', '700'],
  variable: '--font-montserrat', // Creamos una variable CSS
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // return (
  //   <html
  //     lang="en"
  //     className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
  //   >
  //     <body className="min-h-full flex flex-col">{children}</body>
  //   </html>
  // );
  return (
    // Aplicamos la variable de la fuente al HTML
    <html lang="es" className={`${montserrat.variable} font-sans`}>
      <body className="antialiased bg-surface text-on-surface">
        {children}
      </body>
    </html>
  );
  
}
