export const OBSERVATION_FIELDS = [
  { key: "personalInformation.names", label: "Nombres" },
  { key: "personalInformation.fatherLastName", label: "Apellido paterno" },
  { key: "personalInformation.motherLastName", label: "Apellido materno" },
  { key: "personalInformation.birthDate", label: "Fecha de nacimiento" },
  { key: "personalInformation.gender", label: "Género" },
  { key: "personalInformation.phone", label: "Celular" },
  { key: "personalInformation.primaryEmail", label: "Correo principal" },
  { key: "personalInformation.secondaryEmail", label: "Correo secundario" },
  { key: "personalInformation.countryId", label: "País" },
  { key: "personalInformation.departmentId", label: "Departamento" },
  { key: "personalInformation.provinceId", label: "Provincia" },
  { key: "personalInformation.districtId", label: "Distrito" },
  { key: "personalInformation.address", label: "Dirección" },
  { key: "personalInformation.photo", label: "Fotografía" },
  { key: "personalInformation.identityDocument", label: "Documento de identidad" },
  { key: "academicStudies.0.institutionId", label: "Institución de estudios" },
  { key: "academicStudies.0.otherInstitution", label: "Otra institución" },
  { key: "academicStudies.0.degreeTitle", label: "Título o grado" },
  { key: "academicStudies.0.specialty", label: "Especialidad" },
  { key: "academicStudies.0.professionalAssociation", label: "Colegio profesional" },
  { key: "academicStudies.0.registrationNumber", label: "Número de colegiatura" },
  { key: "academicStudies.0.universityLetter", label: "Constancia de estudios" },
  { key: "employmentInformation.companyTaxId", label: "RUC" },
  { key: "employmentInformation.companyName", label: "Empresa" },
  { key: "employmentInformation.area", label: "Área laboral" },
  { key: "employmentInformation.positionName", label: "Cargo" },
  { key: "employmentInformation.workPhone", label: "Teléfono laboral" },
  { key: "employmentInformation.workEmail", label: "Correo laboral" },
  { key: "employmentInformation.workingAddress", label: "Dirección laboral" },
  { key: "endorsements.firstEndorsement.sponsorDocumentNumber", label: "DNI del primer aval" },
  { key: "endorsements.secondEndorsement.sponsorDocumentNumber", label: "DNI del segundo aval" },
  { key: "endorsements.declarationDocumentId", label: "Declaración jurada firmada" },
] as const;

export const OBSERVATION_FIELD_KEYS = new Set<string>(OBSERVATION_FIELDS.map((field) => field.key));
