"use client";
import { Check, ChevronDown, Search } from "lucide-react";
import { useMemo, useState } from "react";

export type Option={id:number;name:string};
export function SearchableSelect({value,options,onChange,placeholder}:{value:string;options:Option[];onChange:(value:string)=>void;placeholder:string}){const[open,setOpen]=useState(false),[query,setQuery]=useState("");const selected=options.find(o=>String(o.id)===value);const filtered=useMemo(()=>options.filter(o=>o.name.toLowerCase().includes(query.toLowerCase())),[options,query]);return <div className="relative"><button type="button" onClick={()=>setOpen(v=>!v)} className="flex h-12 w-full items-center justify-between rounded-xl border border-slate-200 bg-slate-50 px-4 text-left text-sm font-semibold text-slate-700 focus:border-[#C5A059] focus:bg-white focus:outline-none focus:ring-4 focus:ring-[#C5A059]/10">{selected?.name??placeholder}<ChevronDown size={18} className="text-slate-400"/></button>{open&&<div className="absolute z-[80] mt-2 w-full rounded-xl border border-slate-100 bg-white p-2 shadow-[0_15px_40px_-10px_rgba(0,0,0,0.2)]"><div className="relative"><Search size={15} className="absolute left-3 top-3 text-slate-400"/><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar..." className="h-10 w-full rounded-lg border border-slate-200 bg-slate-50 pl-9 pr-3 text-sm outline-none focus:border-[#C5A059]"/></div><div className="mt-1 max-h-56 overflow-y-auto">{filtered.map(option=><button type="button" key={option.id} onClick={()=>{onChange(String(option.id));setOpen(false);setQuery("")}} className="flex w-full items-center justify-between rounded-lg px-3 py-2.5 text-left text-sm font-semibold text-slate-600 hover:bg-[#C5A059]/10">{option.name}{String(option.id)===value&&<Check size={16} className="text-[#C5A059]"/>}</button>)}</div></div>}</div>}
export function StyledCheckbox({checked,onChange,label}:{checked:boolean;onChange:(value:boolean)=>void;label:string}){return <label className="flex cursor-pointer items-center gap-2 text-sm font-semibold text-slate-700"><button type="button" role="checkbox" aria-checked={checked} onClick={()=>onChange(!checked)} className={`flex h-5 w-5 items-center justify-center rounded-md border transition ${checked?"border-[#C5A059] bg-[#C5A059] text-white":"border-slate-300 bg-white hover:border-[#C5A059]"}`}>{checked&&<Check size={14} strokeWidth={3}/>}</button>{label}</label>}
export function StyledSwitch({checked,onChange,label}:{checked:boolean;onChange:(value:boolean)=>void;label:string}){return <button type="button" role="switch" aria-checked={checked} onClick={()=>onChange(!checked)} className="flex items-center gap-3 text-sm font-semibold text-slate-700"><span className={`relative h-6 w-11 rounded-full transition ${checked?"bg-[#C5A059]":"bg-slate-300"}`}><span className={`absolute top-1 h-4 w-4 rounded-full bg-white shadow transition ${checked?"left-6":"left-1"}`}/></span>{label}</button>}
export function StyledRadio({checked,onChange,label}:{checked:boolean;onChange:()=>void;label:React.ReactNode}){return <button type="button" role="radio" aria-checked={checked} onClick={onChange} className={`flex w-full items-center justify-between rounded-xl border p-4 text-left transition ${checked?"border-[#C5A059] bg-[#C5A059]/10":"border-slate-200 hover:border-[#C5A059]/60"}`}><span className="flex items-center gap-3"><span className={`flex h-5 w-5 items-center justify-center rounded-full border-2 ${checked?"border-[#C5A059]":"border-slate-300"}`}>{checked&&<span className="h-2.5 w-2.5 rounded-full bg-[#C5A059]"/>}</span>{label}</span></button>}
