"use client";

import { useCallback, useEffect, useState } from "react";
import { AlertCircle, Download, RefreshCcw } from "lucide-react";
import { DataEmptyState, DataLoadingState, DataManagementShell, type DataManagementHeaderAction } from "@/modules/shared/Components/DataManagement";
import { AssociateIntegrationDrawer } from "../Components/AssociateIntegrationDrawer";
import { AssociateIntegrationFilters } from "../Components/AssociateIntegrationFilters";
import { AssociateIntegrationPagination } from "../Components/AssociateIntegrationPagination";
import { AssociateIntegrationTable } from "../Components/AssociateIntegrationTable";
import { AssociateIntegrationDetail, AssociateIntegrationRow, emptyAssociateIntegrationFilters } from "../Components/associateIntegration.types";

export const canRetry = (status: string) => status === "RETRYABLE";
export const canRecover = (recoveryCandidate: boolean) => recoveryCandidate;
export function buildAssociateIntegrationsQuery(filters: Record<string, string | number | undefined>) { const params = new URLSearchParams(); Object.entries(filters).forEach(([key, value]) => { if (value !== undefined && value !== "") params.set(key, String(value)); }); return params.toString(); }

export function AssociateIntegrationsView() {
  const [rows, setRows] = useState<AssociateIntegrationRow[]>([]), [total, setTotal] = useState(0), [page, setPage] = useState(1), [pageSize, setPageSize] = useState(20);
  const [filters, setFilters] = useState(emptyAssociateIntegrationFilters), [applied, setApplied] = useState(emptyAssociateIntegrationFilters), [detail, setDetail] = useState<AssociateIntegrationDetail | null>(null);
  const [drawerTab, setDrawerTab] = useState<"Resumen" | "Payload SIE">("Resumen"), [isLoading, setIsLoading] = useState(true), [isDetailLoading, setIsDetailLoading] = useState(false);
  const [confirmRetryId, setConfirmRetryId] = useState<number | null>(null), [confirmRecoveryId, setConfirmRecoveryId] = useState<number | null>(null), [retrying, setRetrying] = useState<number | null>(null), [recovering, setRecovering] = useState<number | null>(null);
  const [error, setError] = useState(""), [message, setMessage] = useState("");

  const load = useCallback(async () => { setError(""); setIsLoading(true); try { const query = buildAssociateIntegrationsQuery({ page, pageSize, ...applied }); const response = await fetch(`/api/security/associate-integrations?${query}`); const body = await response.json(); if (!response.ok) throw new Error(body.message); setRows(body.data ?? []); setTotal(body.pagination?.total ?? 0); } catch { setError("No pudimos cargar las integraciones. Inténtalo nuevamente."); } finally { setIsLoading(false); } }, [page, pageSize, applied]);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);

  const openDetail = async (id: number, tab: "Resumen" | "Payload SIE" = "Resumen") => { setDrawerTab(tab); setIsDetailLoading(true); setDetail(null); try { const response = await fetch(`/api/security/associate-integrations/${id}`); const body = await response.json(); if (response.ok) setDetail(body.data); else setMessage("No fue posible cargar el detalle de la integración."); } finally { setIsDetailLoading(false); } };
  const refreshAfterAction = async (id: number) => { await load(); if (detail?.integrationId === id) await openDetail(id); };
  const retry = async (id: number) => { setRetrying(id); setConfirmRetryId(null); try { const response = await fetch(`/api/security/associate-integrations/${id}/retry`, { method: "POST" }); const body = await response.json(); if (response.status === 409) setMessage("La integración ya está siendo procesada o su estado cambió. Actualizamos la información."); else if (!response.ok) setMessage(body.message ?? "No fue posible realizar el reintento."); else if (body.data?.status === "SYNCED") setMessage("Integración sincronizada correctamente."); else if (body.data?.status === "FAILED") setMessage("La integración requiere revisión antes de volver a intentarse."); else setMessage("El envío no se completó. El estado quedó actualizado para su seguimiento."); await refreshAfterAction(id); } finally { setRetrying(null); } };
  const recover = async (id: number) => { setRecovering(id); setConfirmRecoveryId(null); try { const response = await fetch(`/api/security/associate-integrations/${id}/recover-pre-dispatch`, { method: "POST" }); const body = await response.json(); if (!response.ok) setMessage(body.message ?? "No fue posible recuperar la integración."); else if (body.data?.reconciliation === "MATCH" && body.data?.status === "SYNCED") setMessage("La integración ya existe en SIE y fue reconciliada correctamente."); else if (body.data?.reconciliation === "ABSENT" && body.data?.status === "RETRYABLE") setMessage("Integración recuperada correctamente. El caso quedó disponible para un reintento controlado."); else setMessage("La integración fue recuperada y su estado fue actualizado."); await refreshAfterAction(id); } finally { setRecovering(null); } };
  const hasFilters = Object.values(filters).some(Boolean);
  const headerActions: DataManagementHeaderAction[] = [{ key: "export", label: "Exportar Excel", icon: Download, tooltip: "Requiere una exportación completa del listado filtrado.", onClick: () => setMessage("La exportación completa requiere un endpoint que entregue todos los registros filtrados.") }];
  const closeDrawer = () => { setDetail(null); setIsDetailLoading(false); };
  return <DataManagementShell title="Inscripciones SIE" description="Seguimiento y control de las inscripciones enviadas al sistema SIE." resultCount={total} compactSpacing headerActions={headerActions} filters={<AssociateIntegrationFilters values={filters} loading={isLoading} onChange={setFilters} onApply={() => { setPage(1); setApplied(filters); }} onClear={() => { setFilters(emptyAssociateIntegrationFilters); setApplied(emptyAssociateIntegrationFilters); setPage(1); }} />}>
    {message && <p role="status" className="rounded-xl border border-blue-100 bg-blue-50 p-3 text-sm font-bold text-blue-800">{message}</p>}
    {error ? <section className="flex min-h-64 flex-col items-center justify-center gap-3 rounded-2xl border border-slate-200 bg-white p-8 text-center shadow-sm"><AlertCircle size={34} className="text-rose-400" /><div><h2 className="font-black text-slate-800">No pudimos cargar las integraciones</h2><p className="mt-1 text-sm text-slate-500">Verifica tu conexión e inténtalo nuevamente.</p></div><button onClick={() => void load()} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-2 text-sm font-bold text-slate-700 shadow-sm hover:bg-slate-50"><RefreshCcw size={15} /> Reintentar carga</button></section> : isLoading ? <section className="rounded-2xl border border-slate-200 bg-white shadow-sm"><DataLoadingState /></section> : rows.length === 0 ? <DataEmptyState title="No se encontraron inscripciones SIE" description="Ajusta los filtros o espera nuevas inscripciones generadas por el flujo de afiliación." action={hasFilters ? <button onClick={() => { setFilters(emptyAssociateIntegrationFilters); setApplied(emptyAssociateIntegrationFilters); setPage(1); }} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-2 text-sm font-bold text-slate-700 hover:bg-slate-50"><RefreshCcw size={15} /> Limpiar filtros</button> : undefined} /> : <><AssociateIntegrationTable rows={rows} onOpenDetail={(id, tab) => void openDetail(id, tab)} onRetry={setConfirmRetryId} /><AssociateIntegrationPagination total={total} page={page} pageSize={pageSize} onPageChange={setPage} onPageSizeChange={setPageSize} /></>}
    <AssociateIntegrationDrawer key={`${detail?.integrationId ?? "loading"}-${drawerTab}`} detail={detail} loading={isDetailLoading} retrying={retrying !== null} recovering={recovering !== null} initialTab={drawerTab} onClose={closeDrawer} onRetry={setConfirmRetryId} onRecover={setConfirmRecoveryId} />
    {confirmRetryId !== null && <Confirmation title="¿Reintentar sincronización?" description="Se volverá a enviar esta afiliación a SIE. El pago y la aprobación interna no se modificarán." confirmLabel="Confirmar reintento" busy={retrying !== null} onCancel={() => setConfirmRetryId(null)} onConfirm={() => void retry(confirmRetryId)} />}
    {confirmRecoveryId !== null && <Confirmation title="Recuperar integración SIE" description="Esta acción verificará nuevamente el estado del asociado en SIE y recuperará únicamente una integración que haya fallado antes del envío. Esta acción no enviará una nueva alta a SIE." confirmLabel="Recuperar integración" busy={recovering !== null} onCancel={() => setConfirmRecoveryId(null)} onConfirm={() => void recover(confirmRecoveryId)} />}
  </DataManagementShell>;
}

function Confirmation({ title, description, confirmLabel, busy, onCancel, onConfirm }: { title: string; description: string; confirmLabel: string; busy: boolean; onCancel: () => void; onConfirm: () => void }) { return <div role="dialog" aria-modal="true" aria-label={title} className="fixed inset-0 z-50 grid place-items-center bg-slate-950/45 p-4"><div className="w-full max-w-md overflow-hidden rounded-2xl bg-white shadow-2xl"><header className="border-b border-slate-100 px-5 py-4"><h2 className="font-black text-slate-800">{title}</h2></header><div className="p-5"><p className="text-sm leading-6 text-slate-600">{description}</p><div className="mt-6 flex justify-end gap-2"><button disabled={busy} onClick={onCancel} className="rounded-lg px-4 py-2 text-sm font-bold text-slate-600 hover:bg-slate-50 disabled:opacity-60">Cancelar</button><button disabled={busy} onClick={onConfirm} className="rounded-lg bg-[#C5A059] px-4 py-2 text-sm font-bold text-white disabled:opacity-60">{busy ? "Procesando..." : confirmLabel}</button></div></div></div></div>; }
