"use client";

import { AlertCircle, CalendarDays, CheckCircle2, ChevronRight, Clock3, CreditCard, Edit3, History, LoaderCircle, Mail, Palette, ToggleLeft, WalletCards } from "lucide-react";
import { useMemo, useState, type ReactNode } from "react";
import { toast } from "sonner";
import { PaymentSettingEditor, type PaymentSettingEditorState } from "../Components/PaymentSettingEditor";
import { PaymentTechnicalDetailsModal } from "../Components/PaymentTechnicalDetailsModal";
import { useSystemSettings } from "../Hooks/useSystemSettings";
import { SETTING_PRESENTATION, type SystemSettingValueViewModel, type SystemSettingViewModel } from "../Models/SystemSettingsViewModel";
import type { PaymentConfigurationSource } from "../Services/PaymentConfigurationHealthService";

interface AuditLogViewModel { id: string; action: string; entityId: string | null; oldValues: unknown; newValues: unknown; createdAt: string | Date; user?: { person?: { firstName: string; paternalLastName: string } | null } | null; }
const K = { registration: "PAYMENT_REGISTRATION_PRICE", monthly: "PAYMENT_MONTHLY_FEE", enabled: "PAYMENTS_ENABLED", startsAt: "PAYMENT_START_AT", endsAt: "PAYMENT_END_AT", cards: "CARD_ENABLED", merchantName: "NIUBIZ_MERCHANT_NAME", logoUrl: "NIUBIZ_CHECKOUT_LOGO_URL", color: "NIUBIZ_FORM_BUTTON_COLOR", expiration: "NIUBIZ_SESSION_EXPIRATION_MINUTES", emailEnabled: "PAYMENT_CONFIRMATION_EMAIL_ENABLED", emailSubject: "PAYMENT_CONFIRMATION_EMAIL_SUBJECT" } as const;
const criticalKeys: string[] = [K.registration, K.monthly, K.enabled, K.startsAt, K.endsAt, K.cards];
const money = (value: string | number | null | undefined) => value === null || value === undefined || value === "" ? "Pendiente de configurar" : new Intl.NumberFormat("es-PE", { style: "currency", currency: "PEN" }).format(Number(value));
const formatDate = (value: string | null | undefined) => value ? new Intl.DateTimeFormat("es-PE", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : null;
const actionButton = "inline-flex items-center gap-2 rounded-xl border border-[#E6C982] bg-white px-3.5 py-2 text-sm font-bold text-[#936B2E] transition hover:bg-[#FFF8E8]";

function valueFromAudit(raw: unknown) { if (!raw || typeof raw !== "object" || !("value" in raw)) return null; const value = (raw as { value?: unknown }).value; return typeof value === "string" || typeof value === "number" || typeof value === "boolean" ? String(value) : null; }
function displayValue(setting: SystemSettingViewModel, value: string | null) { if (value === null) return "Pendiente de configurar"; if (setting.dataType === "MONEY") return money(value); if (setting.dataType === "BOOLEAN") return value === "true" ? "Activado" : "Desactivado"; if (setting.dataType === "DATETIME") return formatDate(value) ?? "Pendiente de configurar"; if (setting.key === K.expiration) return `${value} minutos`; return value; }
function sourceLabel(source: PaymentConfigurationSource | undefined) { return source === "TEST_FALLBACK" ? "Valor de prueba" : source === "MISSING" ? "Pendiente de configurar" : null; }
function currentValue(setting: SystemSettingViewModel): SystemSettingValueViewModel | undefined { return setting.currentValueId && setting.currentValue !== null && setting.currentStartsAt ? { id: setting.currentValueId, value: setting.currentValue, startsAt: setting.currentStartsAt, endsAt: setting.currentEndsAt, isActive: true } : undefined; }

export function SystemSettingsView({ initialAuditLogs }: { initialAuditLogs: AuditLogViewModel[] }) {
  const { settings, environment, health, loading, error, create, update } = useSystemSettings();
  const [editor, setEditor] = useState<PaymentSettingEditorState | null>(null);
  const [technicalOpen, setTechnicalOpen] = useState(false);
  const [historyOpen, setHistoryOpen] = useState(false);
  const byKey = useMemo(() => new Map(settings.map((setting) => [setting.key, setting])), [settings]);
  const futureChanges = useMemo(() => settings.flatMap((setting) => setting.futureValues.map((value) => ({ setting, value }))).sort((a, b) => new Date(a.value.startsAt).getTime() - new Date(b.value.startsAt).getTime()), [settings]);
  const valueNames = useMemo(() => new Map(settings.flatMap((setting) => [setting.currentValueId, ...setting.futureValues.map((value) => value.id), ...setting.historicalValues.map((value) => value.id)].filter((id): id is number => typeof id === "number").map((id) => [String(id), setting]))), [settings]);
  const get = (key: string) => byKey.get(key);
  const check = (key: string) => health?.checks.find((item) => item.key === key);
  const effective = (key: string) => get(key)?.currentValue ?? (check(key)?.value !== undefined ? String(check(key)?.value) : null);
  const registration = get(K.registration), monthly = get(K.monthly), enabled = get(K.enabled), startsAt = get(K.startsAt), endsAt = get(K.endsAt), cards = get(K.cards), merchantName = get(K.merchantName), logoUrl = get(K.logoUrl), color = get(K.color), expiration = get(K.expiration), emailEnabled = get(K.emailEnabled), emailSubject = get(K.emailSubject);
  const activePayments = effective(K.enabled) !== "false";
  const period = formatPeriod(startsAt?.currentValue ?? null, endsAt?.currentValue ?? null);
  const missing = environment === "PRODUCTION" ? health?.missing.slice(0, 3) ?? [] : [];

  const save = async (setting: SystemSettingViewModel, value: SystemSettingValueViewModel | undefined, payload: { value: string; startsAt: string; endsAt: string | null; isActive: boolean }) => {
    const critical = criticalKeys.includes(setting.key);
    if (critical && !window.confirm(`¿Confirmas este cambio?\n\n${displayValue(setting, value?.value ?? setting.currentValue)} → ${displayValue(setting, payload.value)}`)) return;
    try { if (value) await update(value.id, payload); else await create(setting.key, payload); toast.success("Cambio guardado correctamente."); setEditor(null); }
    catch (cause) { toast.error(cause instanceof Error ? cause.message : "No se pudo guardar el cambio."); }
  };
  const toggle = async (setting: SystemSettingViewModel, next: boolean) => {
    if (!setting.hasCurrentValue || !setting.currentValueId || !setting.currentStartsAt) { setEditor({ setting, initialValue: String(next) }); return; }
    if (!window.confirm(next ? "¿Permitir pagos?" : "¿Desactivar los pagos? Los postulantes no podrán iniciar nuevos pagos.")) return;
    try { await update(setting.currentValueId, { value: String(next), startsAt: setting.currentStartsAt, endsAt: setting.currentEndsAt, isActive: true }); toast.success("Disponibilidad actualizada."); }
    catch (cause) { toast.error(cause instanceof Error ? cause.message : "No se pudo actualizar la disponibilidad."); }
  };

  return <div className="space-y-7 pb-12 animate-in fade-in duration-500">
    <header className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><h1 className="text-3xl font-black tracking-tight text-slate-800">Configuración de pagos</h1><p className="mt-1.5 text-sm font-medium text-slate-500">Administra precios, disponibilidad, métodos de pago y confirmaciones.</p></div><div className="rounded-xl border border-slate-200 bg-white px-3.5 py-2 text-xs font-semibold text-slate-500 shadow-sm">Entorno: <span className="font-black text-slate-700">{environment}</span></div></header>
    {loading ? <LoadingState/> : <>
      <section className="grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-4">
        <SummaryCard icon={<CheckCircle2 size={19}/>} label="Estado de pagos" value={health?.status === "INCOMPLETE" && environment === "PRODUCTION" ? "Requiere configuración" : activePayments ? "Pagos habilitados" : "Pagos deshabilitados"} description={activePayments ? "Los postulantes pueden realizar pagos." : "No se pueden iniciar nuevos pagos."} tone={activePayments ? "success" : "neutral"}/>
        <SummaryCard icon={<WalletCards size={19}/>} label="Precio de inscripción" value={money(effective(K.registration))} description="Inscripción de nuevos asociados" badge={sourceLabel(check(K.registration)?.source) ?? undefined}/>
        <SummaryCard icon={<CalendarDays size={19}/>} label="Periodo de pagos" value={period.title} description="Periodo disponible para realizar pagos"/>
        <SummaryCard icon={<CreditCard size={19}/>} label="Métodos disponibles" value={effective(K.cards) === "false" ? "Pendiente de activar" : "Tarjetas"} description="Pagos con tarjeta mediante Niubiz"/>
      </section>
      {missing.length > 0 && <section className="flex flex-col gap-4 rounded-2xl border border-amber-200 bg-amber-50/60 p-5 sm:flex-row sm:items-center sm:justify-between"><div className="flex gap-3"><AlertCircle className="mt-0.5 shrink-0 text-amber-700" size={21}/><div><h2 className="font-black text-slate-800">Configuración pendiente</h2><p className="mt-1 text-sm text-slate-600">Hay {missing.length} ajuste{missing.length === 1 ? "" : "s"} que debes completar antes de habilitar pagos en producción.</p><ul className="mt-2 list-inside list-disc text-xs leading-5 text-slate-600">{missing.map((item) => <li key={item}>{humanizeMissing(item)}</li>)}</ul></div></div><button onClick={() => document.getElementById("payment-settings")?.scrollIntoView({ behavior: "smooth" })} className={actionButton}>Revisar pendientes <ChevronRight size={16}/></button></section>}
      {error && <div className="flex items-center gap-2 rounded-xl border border-red-200 bg-red-50 p-4 text-sm font-bold text-red-700"><AlertCircle size={18}/>{error}</div>}
      <div id="payment-settings" className="space-y-5">
        <PaymentSection icon={<ToggleLeft size={20}/>} title="Estado y fechas" description="Controla cuándo los postulantes pueden realizar pagos.">
          {enabled && <div className="flex flex-col gap-4 border-b border-slate-100 pb-5 md:flex-row md:items-center md:justify-between"><div><h3 className="text-base font-black text-slate-800">Permitir pagos</h3><p className="mt-1 text-sm text-slate-500">Cuando está desactivado, ningún postulante podrá iniciar un nuevo pago.</p></div><button onClick={() => void toggle(enabled, !activePayments)} className={`inline-flex items-center justify-center gap-2 rounded-xl px-4 py-2.5 text-sm font-black ${activePayments ? "bg-emerald-50 text-emerald-700" : "bg-slate-100 text-slate-600"}`}><span className={`h-2.5 w-2.5 rounded-full ${activePayments ? "bg-emerald-500" : "bg-slate-400"}`}/>{activePayments ? "ACTIVADO" : "DESACTIVADO"}</button></div>}
          <div className="flex flex-col gap-4 pt-5 md:flex-row md:items-end md:justify-between"><div><h3 className="text-base font-black text-slate-800">Periodo disponible</h3><div className="mt-3 grid grid-cols-1 gap-3 sm:grid-cols-2"><PeriodField label="Desde" value={formatDate(startsAt?.currentValue)} onEdit={() => startsAt && setEditor({ setting: startsAt, value: currentValue(startsAt) })}/><PeriodField label="Hasta" value={formatDate(endsAt?.currentValue)} onEdit={() => endsAt && setEditor({ setting: endsAt, value: currentValue(endsAt) })}/></div><p className="mt-3 text-xs text-slate-500">{period.description}</p></div><button onClick={() => startsAt && setEditor({ setting: startsAt, value: currentValue(startsAt) })} className={actionButton}><Edit3 size={15}/>Editar periodo</button></div>
        </PaymentSection>
        <PaymentSection icon={<WalletCards size={20}/>} title="Precios" description="Define los importes utilizados para nuevos pagos."><div className="grid gap-4 md:grid-cols-2"><PriceCard title="Inscripción" value={money(effective(K.registration))} description="Pago único de inscripción" badge={sourceLabel(check(K.registration)?.source) ?? undefined} onEdit={() => registration && setEditor({ setting: registration, value: currentValue(registration), initialValue: effective(K.registration) ?? undefined })}/><PriceCard title="Cuota anual" value={monthly?.currentValue ? money(monthly.currentValue) : "Aún no definido"} description="Cuota anual del asociado" badge="Preparado para futura integración" onEdit={() => monthly && setEditor({ setting: monthly, value: currentValue(monthly) })}/></div></PaymentSection>
        <PaymentSection icon={<CreditCard size={20}/>} title="Métodos de pago" description="Selecciona las formas de pago disponibles para los postulantes."><div className="divide-y divide-slate-100"><MethodRow icon={<CreditCard size={20}/>} title="Tarjetas" description="Visa, Mastercard y métodos soportados por Niubiz" enabled={effective(K.cards) !== "false"} onToggle={() => cards && void toggle(cards, effective(K.cards) === "false")}/><MethodRow icon={<WalletCards size={20}/>} title="Yape" description="La integración todavía no está disponible." disabled enabled={false}/></div></PaymentSection>
        <PaymentSection icon={<Palette size={20}/>} title="Apariencia del pago" description="Personaliza cómo se mostrará la ventana de pago de Niubiz."><div className="grid gap-7 lg:grid-cols-[minmax(0,1.2fr)_minmax(280px,0.8fr)]"><div className="space-y-4"><SettingRow label="Nombre mostrado" value={effective(K.merchantName) ?? "Pendiente de configurar"} description="Nombre que verá el usuario al momento de pagar." onEdit={() => merchantName && setEditor({ setting: merchantName, value: currentValue(merchantName), initialValue: effective(K.merchantName) ?? undefined })}/><SettingRow label="Logo del pago" value={effective(K.logoUrl) ? "Logo configurado" : "Pendiente de configurar"} description="La imagen debe ser pública y accesible mediante HTTPS en producción." onEdit={() => logoUrl && setEditor({ setting: logoUrl, value: currentValue(logoUrl), initialValue: effective(K.logoUrl) ?? undefined })}/><SettingRow label="Color principal" value={effective(K.color) ?? "Pendiente de configurar"} description="Color utilizado en el botón de pago." swatch={effective(K.color) ?? undefined} onEdit={() => color && setEditor({ setting: color, value: currentValue(color), initialValue: effective(K.color) ?? undefined })}/><SettingRow label="Tiempo para completar el pago" value={effective(K.expiration) ? `${effective(K.expiration)} minutos` : "Pendiente de configurar"} description="Tiempo disponible antes de que la sesión de pago expire." onEdit={() => expiration && setEditor({ setting: expiration, value: currentValue(expiration), initialValue: effective(K.expiration) ?? undefined })}/></div><CheckoutPreview name={effective(K.merchantName) ?? "Instituto de Ingenieros de Minas del Perú"} logoUrl={effective(K.logoUrl)} color={effective(K.color) ?? "#C5A059"}/></div></PaymentSection>
        <PaymentSection icon={<Mail size={20}/>} title="Confirmación por correo" description="Configura el mensaje que recibirá el asociado después de un pago aprobado."><div className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_minmax(300px,0.9fr)]"><div className="space-y-5"><div className="flex items-center justify-between gap-4"><div><h3 className="font-black text-slate-800">Enviar confirmación automáticamente</h3><p className="mt-1 text-sm text-slate-500">El correo se enviará únicamente cuando Niubiz confirme el pago.</p></div>{emailEnabled && <button onClick={() => void toggle(emailEnabled, effective(K.emailEnabled) !== "true")} className={`rounded-xl px-3 py-2 text-xs font-black ${effective(K.emailEnabled) === "true" ? "bg-emerald-50 text-emerald-700" : "bg-slate-100 text-slate-600"}`}>{effective(K.emailEnabled) === "true" ? "ACTIVADO" : "DESACTIVADO"}</button>}</div><SettingRow label="Mensaje de confirmación" value={effective(K.emailSubject) ?? "Pendiente de configurar"} description="Asunto que verá el asociado en su correo." onEdit={() => emailSubject && setEditor({ setting: emailSubject, value: currentValue(emailSubject), initialValue: effective(K.emailSubject) ?? undefined })}/></div><EmailPreview subject={effective(K.emailSubject) ?? "Afiliación IIMP confirmada – Pago realizado correctamente"}/></div></PaymentSection>
      </div>
      <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-base font-black text-slate-800">Cambios programados</h2><p className="mt-1 text-sm text-slate-500">Próximos ajustes que se aplicarán automáticamente.</p></div><div className="flex gap-2"><button onClick={() => setTechnicalOpen(true)} className="rounded-xl px-3 py-2 text-xs font-bold text-slate-500 hover:bg-slate-100">Detalles técnicos</button><button onClick={() => setHistoryOpen(true)} className={actionButton}><History size={15}/>Ver historial</button></div></div><div className="mt-4 divide-y divide-slate-100">{futureChanges.slice(0, 5).map(({ setting, value }) => <div key={value.id} className="flex gap-3 py-3"><Clock3 className="mt-0.5 shrink-0 text-[#A67C3B]" size={17}/><div><p className="text-sm font-bold text-slate-700">{describeFuture(setting, value)}</p><p className="mt-1 text-xs text-slate-500">{formatDate(value.startsAt)}</p></div></div>)}{futureChanges.length === 0 && <p className="py-5 text-sm text-slate-500">No hay cambios programados.</p>}</div></section>
    </>}
    {editor && <PaymentSettingEditor editor={editor} onClose={() => setEditor(null)} onSave={save}/>} {technicalOpen && health && <PaymentTechnicalDetailsModal health={health} onClose={() => setTechnicalOpen(false)}/>} {historyOpen && <HistoryModal logs={initialAuditLogs} settingByValueId={valueNames} onClose={() => setHistoryOpen(false)}/>} 
  </div>;
}

function LoadingState() { return <div className="flex items-center justify-center gap-2 py-24 text-sm font-bold text-slate-500"><LoaderCircle className="animate-spin text-[#C5A059]" size={18}/>Cargando configuración de pagos...</div>; }
function SummaryCard({ icon, label, value, description, badge, tone = "default" }: { icon: ReactNode; label: string; value: string; description: string; badge?: string; tone?: "default" | "success" | "neutral" }) { return <article className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className={`inline-flex rounded-xl p-2 ${tone === "success" ? "bg-emerald-50 text-emerald-700" : "bg-[#FFF8E8] text-[#A67C3B]"}`}>{icon}</div><p className="mt-3 text-xs font-bold text-slate-500">{label}</p><p className="mt-1 text-lg font-black tracking-tight text-slate-800">{value}</p><p className="mt-1 text-xs leading-5 text-slate-500">{description}</p>{badge && <span title="Este valor proviene de la configuración temporal del entorno TEST." className="mt-2 inline-flex rounded-full bg-slate-100 px-2 py-1 text-[10px] font-bold text-slate-600">{badge}</span>}</article>; }
function PaymentSection({ icon, title, description, children }: { icon: ReactNode; title: string; description: string; children: ReactNode }) { return <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div className="mb-5 flex gap-3"><div className="h-fit rounded-xl bg-[#FFF8E8] p-2.5 text-[#A67C3B]">{icon}</div><div><h2 className="text-lg font-black text-slate-800">{title}</h2><p className="mt-1 text-sm text-slate-500">{description}</p></div></div>{children}</section>; }
function PeriodField({ label, value, onEdit }: { label: string; value: string | null; onEdit: () => void }) { return <div className="min-w-[190px] rounded-xl border border-slate-200 bg-slate-50 px-3 py-2.5"><div className="flex items-center justify-between gap-3"><span className="text-[11px] font-black uppercase tracking-wide text-slate-400">{label}</span><button onClick={onEdit} className="text-xs font-bold text-[#A67C3B] hover:underline">Editar</button></div><p className="mt-1 text-sm font-bold text-slate-700">{value ?? (label === "Hasta" ? "Sin fecha de cierre" : "Sin restricción de fechas")}</p></div>; }
function PriceCard({ title, value, description, badge, onEdit }: { title: string; value: string; description: string; badge?: string; onEdit: () => void }) { return <article className="rounded-2xl border border-slate-200 bg-slate-50/60 p-5"><p className="text-sm font-black text-slate-800">{title}</p><p className="mt-2 text-2xl font-black tracking-tight text-slate-800">{value}</p><p className="mt-1 text-sm text-slate-500">{description}</p>{badge && <span className="mt-3 inline-block rounded-full bg-[#FFF8E8] px-2.5 py-1 text-[10px] font-bold text-[#936B2E]">{badge}</span>}<div className="mt-4"><button onClick={onEdit} className={actionButton}><Edit3 size={15}/>Editar precio</button></div></article>; }
function MethodRow({ icon, title, description, enabled, disabled, onToggle }: { icon: ReactNode; title: string; description: string; enabled: boolean; disabled?: boolean; onToggle?: () => void }) { return <div className="flex flex-col gap-3 py-4 first:pt-0 sm:flex-row sm:items-center sm:justify-between"><div className="flex gap-3"><div className="rounded-xl bg-slate-100 p-2 text-slate-600">{icon}</div><div><h3 className="font-black text-slate-800">{title}</h3><p className="mt-1 text-sm text-slate-500">{description}</p></div></div>{disabled ? <span className="w-fit rounded-full bg-slate-100 px-3 py-1.5 text-xs font-bold text-slate-500">Próximamente</span> : <button onClick={onToggle} className={`w-fit rounded-xl px-3 py-2 text-xs font-black ${enabled ? "bg-emerald-50 text-emerald-700" : "bg-slate-100 text-slate-600"}`}>{enabled ? "ACTIVO" : "INACTIVO"}</button>}</div>; }
function SettingRow({ label, value, description, swatch, onEdit }: { label: string; value: string; description: string; swatch?: string; onEdit: () => void }) { return <div className="flex flex-col gap-3 rounded-xl border border-slate-100 p-4 sm:flex-row sm:items-center sm:justify-between"><div className="min-w-0"><p className="font-black text-slate-800">{label}</p><div className="mt-1 flex items-center gap-2"><p className="truncate text-sm font-semibold text-slate-600">{value}</p>{swatch && <span className="h-4 w-4 shrink-0 rounded border border-slate-200" style={{ backgroundColor: swatch }}/>}</div><p className="mt-1 text-xs leading-5 text-slate-500">{description}</p></div><button onClick={onEdit} className={`${actionButton} shrink-0`}><Edit3 size={15}/>Editar</button></div>; }
function CheckoutPreview({ name, logoUrl, color }: { name: string; logoUrl: string | null; color: string }) { return <aside className="rounded-2xl border border-slate-200 bg-slate-50 p-5"><p className="text-[11px] font-black uppercase tracking-wider text-slate-400">Vista previa</p><div className="mt-3 rounded-xl bg-white p-5 shadow-sm"><div className="flex items-center gap-3">{logoUrl ? <img /* eslint-disable-line @next/next/no-img-element -- la URL administrable puede pertenecer a cualquier dominio público */ src={logoUrl} alt="Logo del pago" className="h-10 w-16 object-contain"/> : <div className="flex h-10 w-16 items-center justify-center rounded bg-slate-100 text-[10px] font-bold text-slate-400">LOGO</div>}<div><p className="text-sm font-black text-slate-800">{name}</p><p className="text-xs text-slate-500">Pago seguro</p></div></div><div className="mt-6 space-y-2"><div className="h-9 rounded-lg border border-slate-200 bg-slate-50"/><div className="h-9 rounded-lg border border-slate-200 bg-slate-50"/></div><button type="button" className="mt-4 w-full rounded-lg py-2.5 text-sm font-black text-white" style={{ backgroundColor: color }}>Pagar ahora</button></div></aside>; }
function EmailPreview({ subject }: { subject: string }) { return <aside className="rounded-2xl border border-slate-200 bg-slate-50 p-5"><p className="text-[11px] font-black uppercase tracking-wider text-slate-400">Vista previa del correo</p><div className="mt-3 rounded-xl bg-white p-5 text-sm shadow-sm"><p className="font-black text-emerald-700">✓ Pago realizado correctamente</p><p className="mt-4 text-slate-700">Hola, asociado.</p><p className="mt-2 leading-6 text-slate-600">Hemos confirmado tu pago de inscripción.</p><div className="mt-4 grid grid-cols-2 gap-3 rounded-lg bg-slate-50 p-3 text-xs"><span className="text-slate-500">Monto pagado</span><strong className="text-right text-slate-800">S/ 300.00</strong><span className="text-slate-500">Estado</span><strong className="text-right text-emerald-700">Pagado</strong></div><p className="mt-4 text-xs font-semibold text-slate-500">Asunto: {subject}</p></div></aside>; }
function HistoryModal({ logs, settingByValueId, onClose }: { logs: AuditLogViewModel[]; settingByValueId: Map<string, SystemSettingViewModel>; onClose: () => void }) { return <div className="fixed inset-0 z-[100] flex items-center justify-center bg-slate-950/45 p-4 backdrop-blur-sm" role="dialog" aria-modal="true"><div className="max-h-[82vh] w-full max-w-3xl overflow-auto rounded-3xl bg-white shadow-2xl"><div className="sticky top-0 flex items-center justify-between border-b border-slate-100 bg-white p-6"><div><h2 className="text-lg font-black text-slate-800">Historial de cambios</h2><p className="mt-1 text-xs text-slate-500">Cambios realizados en la configuración de pagos.</p></div><button onClick={onClose} className="rounded-lg p-2 text-slate-400 hover:bg-slate-100" aria-label="Cerrar">×</button></div><div className="divide-y divide-slate-100">{logs.map((log) => { const setting = log.entityId ? settingByValueId.get(log.entityId) : undefined; const title = setting ? SETTING_PRESENTATION[setting.key]?.title ?? "Configuración de pagos" : "Configuración de pagos"; const before = setting ? displayValue(setting, valueFromAudit(log.oldValues)) : null; const after = setting ? displayValue(setting, valueFromAudit(log.newValues)) : null; return <article key={log.id} className="p-5"><div className="flex flex-wrap items-center gap-x-3 gap-y-1"><p className="font-black text-slate-800">{log.user?.person ? `${log.user.person.firstName} ${log.user.person.paternalLastName}` : "Sistema"}</p><span className="text-xs text-slate-400">{formatDate(typeof log.createdAt === "string" ? log.createdAt : log.createdAt.toISOString())}</span></div><p className="mt-2 text-sm text-slate-600">{historyAction(log.action, title)}</p>{(before || after) && <p className="mt-1 text-xs font-bold text-slate-500">{before ?? "Sin valor anterior"}{after ? ` → ${after}` : ""}</p>}</article>; })}{logs.length === 0 && <p className="p-10 text-center text-sm font-bold text-slate-500">No hay cambios registrados.</p>}</div></div></div>; }
function formatPeriod(startsAt: string | null, endsAt: string | null) { if (!startsAt && !endsAt) return { title: "Sin fecha límite", description: "Disponible sin restricción de fechas" }; if (!startsAt) return { title: `Hasta ${formatDate(endsAt)}`, description: "Periodo disponible para realizar pagos" }; if (!endsAt) return { title: `Desde ${formatDate(startsAt)}`, description: "Sin fecha de cierre configurada" }; const day = new Intl.DateTimeFormat("es-PE", { day: "2-digit", month: "short" }); return { title: `${day.format(new Date(startsAt))} – ${day.format(new Date(endsAt))}`, description: "Periodo disponible para realizar pagos" }; }
function describeFuture(setting: SystemSettingViewModel, value: SystemSettingValueViewModel) { const title = SETTING_PRESENTATION[setting.key]?.title ?? "La configuración"; return setting.dataType === "BOOLEAN" ? `${title} será ${value.value === "true" ? "habilitado" : "deshabilitado"}.` : `${title} cambiará a ${displayValue(setting, value.value)}.`; }
function historyAction(action: string, title: string) { if (action === "CREATE_SETTING_VALUE") return `Programó o creó ${title.toLowerCase()}.`; if (action === "ENABLE_SETTING_VALUE") return `Habilitó ${title.toLowerCase()}.`; if (action === "DISABLE_SETTING_VALUE") return `Deshabilitó ${title.toLowerCase()}.`; return `Cambió ${title.toLowerCase()}.`; }
function humanizeMissing(value: string) { return value.replace("Inicio de ventana de pagos", "Define la fecha de inicio de pagos.").replace("Fin de ventana de pagos", "Define la fecha de cierre de pagos.").replace("Precio de inscripción vigente", "Define el precio de inscripción.").replace("Merchant Name", "Define el nombre mostrado en el pago."); }
