import { AssociateIntegrationStatus, AssociateIntegrationTrigger } from "@prisma/client";
import { describe, expect, it, vi } from "vitest";
import { AssociatesApiError } from "../Clients/AssociatesApiError";
import type { AssociateIntegrationRecord, AssociateRequestPayloadSnapshot } from "../Models/AssociateIntegration";
import type { AssociateIntegrationError, IAssociateIntegrationRepository } from "../Repositories/Interfaces/IAssociateIntegrationRepository";
import { AssociatesIntegrationService } from "../Services/AssociatesIntegrationService";

const snapshot = { TipoDocumento:"1",NumDocumento:"72183002",Tipo:"A",Nombres:"Ana",ApellidoPaterno:"Perez",ApellidoMaterno:"Diaz",Direccion:"Av. Uno",Telefono:"999",Email:"a@b.com",TipoFacturacion:"03",TipDocFacturacion:"1",NumDocFacturacion:"72183002",ApellidoPaternoFact:"Perez",ApellidoMaternoFact:"Diaz",NombresFact:"Ana",DirFacturacion:"Av. Uno",servicios:[{concepto:"INSCRIPCION",anno:2026,moneda:"S/",monto:150,cortesia:false},{concepto:"CUOTA",anno:2026,moneda:"S/",monto:150,cortesia:false}] } as AssociateRequestPayloadSnapshot;
class Repo implements IAssociateIntegrationRepository { records=new Map<number,AssociateIntegrationRecord>(); audits:any[]=[]; attemptHistory:any[]=[]; constructor(status:AssociateIntegrationStatus=AssociateIntegrationStatus.RETRYABLE){this.records.set(1,this.record(status));} record(status:AssociateIntegrationStatus){return {id:1,applicationId:10,trigger:AssociateIntegrationTrigger.ACTIVE_PAYMENT,status,requestPayloadSnapshot:snapshot,externalAssociateCode:null,externalMessage:null,attempts:0,lastAttemptAt:null,syncedAt:null,lastErrorHttpStatus:null,lastErrorCode:null,lastErrorMessage:null,lastErrorIdentifier:null,lastErrorDetails:null,externalReceiptType:null,externalReceiptSerie:null,externalReceiptNumber:null,externalReceiptPdfReference:null,createdAt:new Date(),updatedAt:new Date()};} async createPendingIfAbsent(){return this.records.get(10)!} async createFailedIfAbsent(){return this.records.get(10)!} async findById(id:number){return this.records.get(id)??null} async findByApplicationId(id:number){return [...this.records.values()].find(x=>x.applicationId===id)??null} async markProcessing(applicationId:number){const r=await this.findByApplicationId(applicationId);if(!r||r.status!==AssociateIntegrationStatus.RETRYABLE)return null;r.status=AssociateIntegrationStatus.PROCESSING;r.attempts++;return r} async markSynced(applicationId:number,result:any){const r=(await this.findByApplicationId(applicationId))!;r.status=AssociateIntegrationStatus.SYNCED;r.externalAssociateCode=result.externalAssociateCode;return r} async markRetryable(applicationId:number,error:AssociateIntegrationError){const r=(await this.findByApplicationId(applicationId))!;r.status=AssociateIntegrationStatus.RETRYABLE;r.lastErrorCode=error.code??null;return r} async markFailed(applicationId:number,error:AssociateIntegrationError){const r=(await this.findByApplicationId(applicationId))!;r.status=AssociateIntegrationStatus.FAILED;r.lastErrorCode=error.code??null;return r} async startAttempt(integrationId:number,startedAt:Date){const attempt={id:this.attemptHistory.length+1,integrationId,attemptNumber:this.attemptHistory.filter(x=>x.integrationId===integrationId).length+1,startedAt,finishedAt:null,result:null,httpStatus:null,errorCode:null,message:null,errorIdentifier:null,errorDetails:null,externalAssociateCode:null,externalMessage:null,durationMs:null};this.attemptHistory.push(attempt);return attempt} async finishAttempt(id:number,outcome:any,finishedAt:Date){const attempt=this.attemptHistory.find(x=>x.id===id);Object.assign(attempt,outcome,{finishedAt});return attempt} async listAdmin(){return {data:[],total:0}} async findAdminById(id:number){const record=await this.findById(id);return record?{...record,attemptHistory:this.attemptHistory,application:{applicationCode:"EXP-1",trackingCode:"TRACK-1",affiliateType:"ACTIVE"}}:null} async createRetryAudit(data:any){this.audits.push(data)} }
describe("AssociateIntegration admin",()=>{
 it("retries once and audits success",async()=>{const repo=new Repo();const client={createAssociate:vi.fn().mockResolvedValue({externalAssociateCode:7})};const service=new AssociatesIntegrationService(repo,undefined,client as never);expect((await service.retryManual(1,99))?.status).toBe("SYNCED");expect(client.createAssociate).toHaveBeenCalledOnce();expect(repo.audits[0]).toMatchObject({userId:99,integrationId:1,result:"SYNCED"});});
 it("allows one concurrent retry only",async()=>{const repo=new Repo();const client={createAssociate:vi.fn().mockResolvedValue({externalAssociateCode:7})};const service=new AssociatesIntegrationService(repo,undefined,client as never);const [a,b]=await Promise.allSettled([service.retryManual(1,1),service.retryManual(1,2)]);expect([a,b].filter(x=>x.status==="fulfilled")).toHaveLength(1);expect(client.createAssociate).toHaveBeenCalledOnce();expect(repo.attemptHistory).toHaveLength(1);});
 it.each(["PENDING","PROCESSING","SYNCED","FAILED"] as const)("blocks %s without HTTP",async(status)=>{const repo=new Repo(status);const client={createAssociate:vi.fn()};await expect(new AssociatesIntegrationService(repo,undefined,client as never).retryManual(1,1)).rejects.toMatchObject({status:409});expect(client.createAssociate).not.toHaveBeenCalled();});
 it("keeps retryable on 500 and fails on 400/403/409",async()=>{for(const [http,status] of [[500,"RETRYABLE"],[400,"FAILED"],[403,"FAILED"],[409,"FAILED"]] as const){const repo=new Repo();const client={createAssociate:vi.fn().mockRejectedValue(new AssociatesApiError("x",{httpStatus:http,retryable:http===500,operation:"CREATE_ASSOCIATE"}))};expect((await new AssociatesIntegrationService(repo,undefined,client as never).retryManual(1,1))?.status).toBe(status);expect(repo.attemptHistory[0]).toMatchObject({httpStatus:http,result:status})}});
 it("keeps retryable on a network timeout",async()=>{const repo=new Repo();const client={createAssociate:vi.fn().mockRejectedValue(new AssociatesApiError("timeout",{code:"NETWORK_TIMEOUT",retryable:true,operation:"CREATE_ASSOCIATE"}))};expect((await new AssociatesIntegrationService(repo,undefined,client as never).retryManual(1,1))?.status).toBe("RETRYABLE");expect(repo.attemptHistory[0]).toMatchObject({result:"RETRYABLE",errorCode:"NETWORK_TIMEOUT"});});
 it("records one sanitized logical attempt per retry and orders later retries",async()=>{const repo=new Repo();const client={createAssociate:vi.fn().mockRejectedValueOnce(new AssociatesApiError("Bearer secret user@example.com 72183002",{httpStatus:500,code:"SIE_500",details:["token=secret","documento 72183002"],retryable:true,operation:"CREATE_ASSOCIATE"})).mockResolvedValueOnce({externalAssociateCode:7,externalMessage:"ok"})};const service=new AssociatesIntegrationService(repo,undefined,client as never);await service.retryManual(1,1);await service.retryManual(1,1);expect(repo.attemptHistory).toHaveLength(2);expect(repo.attemptHistory.map(x=>x.attemptNumber)).toEqual([1,2]);expect(repo.attemptHistory[0]).toMatchObject({result:"RETRYABLE",httpStatus:500,errorCode:"SIE_500"});expect(JSON.stringify(repo.attemptHistory[0])).not.toContain("secret");expect(JSON.stringify(repo.attemptHistory[0])).not.toContain("user@example.com");expect(repo.attemptHistory[1]).toMatchObject({result:"SYNCED",externalAssociateCode:7});});
 it("returns attempt history newest first without raw error details",async()=>{const repo=new Repo();const client={createAssociate:vi.fn().mockRejectedValueOnce(new AssociatesApiError("x",{httpStatus:500,retryable:true,operation:"CREATE_ASSOCIATE"})).mockResolvedValueOnce({externalAssociateCode:7})};const service=new AssociatesIntegrationService(repo,undefined,client as never);await service.retryManual(1,1);await service.retryManual(1,1);const detail=await service.detailAdmin(1) as any;expect(detail.attemptHistory.map((x:any)=>x.attemptNumber)).toEqual([2,1]);expect(JSON.stringify(detail.attemptHistory)).not.toContain("errorDetails");});
});
