"use client";

import { Check, ChevronDown, Search } from "lucide-react";
import { useEffect, useId, useMemo, useRef, useState } from "react";

export type AppSelectOption = { value: string | number; label: string };
type Props = { label?: string; value: string | number; options: AppSelectOption[]; placeholder?: string; onChange: (value: string) => void; disabled?: boolean; error?: string; required?: boolean; helperText?: string; className?: string; searchable?: boolean; "aria-label"?: string };

export function AppSelect({ label, value, options, placeholder = "Seleccione una opción", onChange, disabled = false, error, required = false, helperText, className = "", searchable = false, "aria-label": ariaLabel }: Props) {
  const id = useId(), rootRef = useRef<HTMLDivElement>(null), searchRef = useRef<HTMLInputElement>(null);
  const [open, setOpen] = useState(false), [query, setQuery] = useState(""), [activeIndex, setActiveIndex] = useState(-1);
  const selected = options.find(option => String(option.value) === String(value));
  const filtered = useMemo(() => searchable ? options.filter(option => option.label.toLocaleLowerCase("es").includes(query.toLocaleLowerCase("es"))) : options, [options, query, searchable]);
  useEffect(() => { if (!open) return; const close = (event: MouseEvent) => { if (!rootRef.current?.contains(event.target as Node)) setOpen(false); }; document.addEventListener("mousedown", close); return () => document.removeEventListener("mousedown", close); }, [open]);
  useEffect(() => { if (open && searchable) searchRef.current?.focus(); }, [open, searchable]);
  const choose = (next: string | number) => { onChange(String(next)); setOpen(false); setQuery(""); };
  const onKeyDown = (event: React.KeyboardEvent<HTMLButtonElement>) => {
    if (disabled) return;
    if (event.key === "Escape") { setOpen(false); return; }
    if (event.key === "Enter" || event.key === " ") { event.preventDefault(); setOpen(value => !value); return; }
    if (event.key === "ArrowDown" || event.key === "ArrowUp") { event.preventDefault(); if (!open) { setOpen(true); setActiveIndex(0); return; } const move = event.key === "ArrowDown" ? 1 : -1; setActiveIndex(index => Math.max(0, Math.min(filtered.length - 1, index + move))); }
  };
  return <div ref={rootRef} className={`relative ${className}`}><label htmlFor={id} className={label ? "mb-1.5 block text-[10px] font-bold uppercase tracking-[.13em] text-slate-500" : "sr-only"}>{label}{required && <span aria-hidden="true"> *</span>}</label><button id={id} type="button" disabled={disabled} aria-label={ariaLabel ?? label} aria-haspopup="listbox" aria-expanded={open} aria-controls={`${id}-options`} onClick={() => setOpen(value => !value)} onKeyDown={onKeyDown} className={`flex h-10 w-full items-center justify-between rounded-xl border bg-white px-3 text-left text-sm outline-none transition hover:border-slate-300 focus:border-[#b48a37] focus:ring-2 focus:ring-[#b48a37]/15 disabled:cursor-not-allowed disabled:bg-slate-50 disabled:text-slate-400 ${error ? "border-red-300" : "border-slate-200"}`}><span className={selected ? "font-medium text-[#172a45]" : "text-slate-400"}>{selected?.label ?? placeholder}</span><ChevronDown size={16} className={`shrink-0 text-slate-400 transition ${open ? "rotate-180" : ""}`} /></button>{open && <div className="absolute z-50 mt-1 w-full overflow-hidden rounded-xl border border-slate-200 bg-white p-1 shadow-xl" role="presentation">{searchable && <div className="relative border-b border-slate-100 p-2"><Search size={15} className="pointer-events-none absolute left-4 top-4 text-slate-400" /><input ref={searchRef} value={query} onChange={event => { setQuery(event.target.value); setActiveIndex(0); }} onKeyDown={event => { if (event.key === "Escape") setOpen(false); if (event.key === "Enter" && filtered[activeIndex]) choose(filtered[activeIndex].value); }} className="w-full rounded-lg bg-slate-50 py-2 pl-8 pr-2 text-sm outline-none focus:ring-2 focus:ring-[#b48a37]/15" placeholder="Buscar..." aria-label={`Buscar ${label ?? "opciones"}`} /></div>}<ul id={`${id}-options`} role="listbox" aria-label={label} className="max-h-56 overflow-y-auto py-1">{filtered.length ? filtered.map((option, index) => { const isSelected = String(option.value) === String(value); return <li key={String(option.value)} role="option" aria-selected={isSelected}><button type="button" onMouseEnter={() => setActiveIndex(index)} onClick={() => choose(option.value)} className={`flex w-full items-center justify-between rounded-lg px-3 py-2.5 text-left text-sm ${isSelected ? "bg-[#fbf4e7] font-semibold text-[#172a45]" : activeIndex === index ? "bg-slate-50 text-[#172a45]" : "text-slate-600 hover:bg-slate-50"}`}>{option.label}{isSelected && <Check size={15} className="text-[#b48a37]" />}</button></li>; }) : <li className="px-3 py-3 text-sm text-slate-500">No se encontraron resultados.</li>}</ul></div>}{error ? <p className="mt-1 text-xs text-red-600">{error}</p> : helperText ? <p className="mt-1 text-xs text-slate-500">{helperText}</p> : null}</div>;
}
